import type { FileNode } from "@nextdj/file-explorer";

export interface StorageItem {
  id: string;
  name: string;
}

export type StorageResponseData = StorageItem[];

export type DemoFileRecord = FileNode & {
  storageId: string;
};

export interface DemoDatabase {
  storages: StorageResponseData;
  files: DemoFileRecord[];
}

export const DEMO_DB_KEY = "file-explorer-demo-db-v4";

export const DEMO_TOTAL_BYTES = 512 * 1024 * 1024;

export const createSeedDatabase = (): DemoDatabase => ({
  storages: [
    { id: "1", name: "Design Drive" },
    { id: "2", name: "Marketing Vault" },
    { id: "3", name: "Local Demo Space" },
  ],
  files: [
    {
      id: "folder_brand",
      storageId: "1",
      name: "Brand Assets",
      type: "folder",
      parentId: undefined,
      updatedAt: "2026-04-16T09:30:00.000Z",
      isHidden: false,
      tagColors: ["blue"],
    },
    {
      id: "folder_social",
      storageId: "1",
      name: "Social Media",
      type: "folder",
      parentId: undefined,
      updatedAt: "2026-04-15T08:10:00.000Z",
      isHidden: false,
      tagColors: ["green"],
    },
    {
      id: "folder_campaign",
      storageId: "1",
      name: "Spring Campaign",
      type: "folder",
      parentId: "folder_social",
      updatedAt: "2026-04-14T11:45:00.000Z",
      isHidden: false,
      tagColors: ["yellow"],
    },
    {
      id: "root_file_hero_banner",
      storageId: "1",
      name: "hero-banner.jpg",
      type: "file",
      parentId: undefined,
      size: 4_120_550,
      extension: "jpg",
      updatedAt: "2026-04-18T09:00:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/jpeg",
      tagColors: ["green"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/a/a9/Example.jpg",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/a/a9/Example.jpg",
      },
    },
    {
      id: "root_file_team_photo",
      storageId: "1",
      name: "team-photo.png",
      type: "file",
      parentId: undefined,
      size: 2_840_300,
      extension: "png",
      updatedAt: "2026-04-18T09:05:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/png",
      tagColors: ["blue"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/1280px-PNG_transparency_demonstration_1.png",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/1280px-PNG_transparency_demonstration_1.png",
      },
    },
    {
      id: "root_file_showcase_board",
      storageId: "1",
      name: "showcase-board.webp",
      type: "file",
      parentId: undefined,
      size: 1_620_440,
      extension: "webp",
      updatedAt: "2026-04-18T09:08:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/webp",
      tagColors: ["yellow"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Wilhelmshaven_Haven.jpg/1280px-Wilhelmshaven_Haven.jpg",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Wilhelmshaven_Haven.jpg/1280px-Wilhelmshaven_Haven.jpg",
      },
    },
    {
      id: "root_file_mountain_shot",
      storageId: "1",
      name: "mountain-shot.jpeg",
      type: "file",
      parentId: undefined,
      size: 5_020_120,
      extension: "jpeg",
      updatedAt: "2026-04-18T09:12:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/jpeg",
      tagColors: ["red"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg",
      },
    },
    {
      id: "root_file_city_night",
      storageId: "1",
      name: "city-night.png",
      type: "file",
      parentId: undefined,
      size: 3_220_920,
      extension: "png",
      updatedAt: "2026-04-18T09:18:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/png",
      tagColors: ["gray"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tokyo_Tower_and_surrounding_buildings.jpg/1280px-Tokyo_Tower_and_surrounding_buildings.jpg",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tokyo_Tower_and_surrounding_buildings.jpg/1280px-Tokyo_Tower_and_surrounding_buildings.jpg",
      },
    },
    {
      id: "root_file_office_walkthrough",
      storageId: "1",
      name: "office-walkthrough.mp4",
      type: "file",
      parentId: undefined,
      size: 24_880_000,
      extension: "mp4",
      updatedAt: "2026-04-18T09:22:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/mp4",
      tagColors: ["green"],
      metadata: {
        previewUrl: "https://download.samplelib.com/mp4/sample-10s.mp4",
        sourceUrl: "https://download.samplelib.com/mp4/sample-10s.mp4",
      },
    },
    {
      id: "root_file_flower_loop",
      storageId: "1",
      name: "flower-loop.webm",
      type: "file",
      parentId: undefined,
      size: 6_540_200,
      extension: "webm",
      updatedAt: "2026-04-18T09:26:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/webm",
      tagColors: ["blue"],
      metadata: {
        previewUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
        sourceUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
      },
    },
    {
      id: "root_file_product_reel",
      storageId: "1",
      name: "product-reel.mov",
      type: "file",
      parentId: undefined,
      size: 15_740_100,
      extension: "mov",
      updatedAt: "2026-04-18T09:30:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/quicktime",
      tagColors: ["yellow"],
      metadata: {
        previewUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
        sourceUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
      },
    },
    {
      id: "root_file_quick_cut",
      storageId: "1",
      name: "quick-cut.mp4",
      type: "file",
      parentId: undefined,
      size: 5_240_880,
      extension: "mp4",
      updatedAt: "2026-04-18T09:34:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/mp4",
      tagColors: ["gray"],
      metadata: {
        previewUrl: "https://download.samplelib.com/mp4/sample-5s.mp4",
        sourceUrl: "https://download.samplelib.com/mp4/sample-5s.mp4",
      },
    },
    {
      id: "root_file_founder_note",
      storageId: "1",
      name: "founder-note.mp3",
      type: "file",
      parentId: undefined,
      size: 4_180_000,
      extension: "mp3",
      updatedAt: "2026-04-18T09:38:00.000Z",
      isHidden: false,
      mediaType: "audio",
      mimeType: "audio/mpeg",
      tagColors: ["gray"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/mp3/sample-6s.mp3",
      },
    },
    {
      id: "root_file_podcast_intro",
      storageId: "1",
      name: "podcast-intro.m4a",
      type: "file",
      parentId: undefined,
      size: 12_510_294,
      extension: "m4a",
      updatedAt: "2026-04-18T09:42:00.000Z",
      isHidden: false,
      mediaType: "audio",
      mimeType: "audio/mp4",
      tagColors: ["blue"],
      metadata: {
        sourceUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3",
      },
    },
    {
      id: "root_file_room_tone",
      storageId: "1",
      name: "room-tone.wav",
      type: "file",
      parentId: undefined,
      size: 8_210_400,
      extension: "wav",
      updatedAt: "2026-04-18T09:46:00.000Z",
      isHidden: false,
      mediaType: "audio",
      mimeType: "audio/wav",
      tagColors: ["yellow"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/wav/sample-3s.wav",
      },
    },
    {
      id: "root_file_brainstorm_clip",
      storageId: "1",
      name: "brainstorm-clip.mp3",
      type: "file",
      parentId: undefined,
      size: 102_400,
      extension: "mp3",
      updatedAt: "2026-04-18T09:50:00.000Z",
      isHidden: false,
      mediaType: "audio",
      mimeType: "audio/mpeg",
      tagColors: ["red"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/mp3/sample-3s.mp3",
      },
    },
    {
      id: "root_file_handbook_pdf",
      storageId: "1",
      name: "team-handbook.pdf",
      type: "file",
      parentId: undefined,
      size: 18_880_512,
      extension: "pdf",
      updatedAt: "2026-04-18T09:54:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/pdf",
      tagColors: ["red"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/pdf/sample-large.pdf",
      },
    },
    {
      id: "root_file_pitch_deck",
      storageId: "1",
      name: "sales-pitch.pptx",
      type: "file",
      parentId: undefined,
      size: 25_428_000,
      extension: "pptx",
      updatedAt: "2026-04-18T09:58:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      tagColors: ["yellow"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/ppt/sample-ppt-500kB.ppt",
      },
    },
    {
      id: "root_file_pricing_sheet",
      storageId: "1",
      name: "pricing-sheet.xlsx",
      type: "file",
      parentId: undefined,
      size: 1_202_111,
      extension: "xlsx",
      updatedAt: "2026-04-18T10:02:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      tagColors: ["green"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/xlsx/sample-500kb.xlsx",
      },
    },
    {
      id: "root_file_launch_brief",
      storageId: "1",
      name: "launch-brief.docx",
      type: "file",
      parentId: undefined,
      size: 2_140_200,
      extension: "docx",
      updatedAt: "2026-04-18T10:06:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      tagColors: ["blue"],
      metadata: {
        sourceUrl: "https://calibre-ebook.com/downloads/demos/demo.docx",
      },
    },
    {
      id: "root_file_script_doc",
      storageId: "1",
      name: "script-outline.doc",
      type: "file",
      parentId: undefined,
      size: 84_220,
      extension: "doc",
      updatedAt: "2026-04-18T10:10:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/msword",
      tagColors: ["gray"],
      metadata: {
        sourceUrl: "https://calibre-ebook.com/downloads/demos/demo.docx",
      },
    },
    {
      id: "root_file_notes_md",
      storageId: "1",
      name: "release-notes.md",
      type: "file",
      parentId: undefined,
      size: 9_240,
      extension: "md",
      updatedAt: "2026-04-18T10:14:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "text/markdown",
      tagColors: ["blue"],
    },
    {
      id: "root_file_story_outline",
      storageId: "1",
      name: "story-outline.txt",
      type: "file",
      parentId: undefined,
      size: 18_020,
      extension: "txt",
      updatedAt: "2026-04-18T10:18:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "text/plain",
      tagColors: ["gray"],
      metadata: {
        sourceUrl: "https://www.w3.org/TR/PNG/iso_8859-1.txt",
      },
    },
    {
      id: "root_file_calendar_csv",
      storageId: "1",
      name: "content-calendar.csv",
      type: "file",
      parentId: undefined,
      size: 45_120,
      extension: "csv",
      updatedAt: "2026-04-18T10:22:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "text/csv",
      tagColors: ["yellow"],
    },
    {
      id: "root_file_rules_json",
      storageId: "1",
      name: "publishing-rules.json",
      type: "file",
      parentId: undefined,
      size: 18_240,
      extension: "json",
      updatedAt: "2026-04-18T10:26:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/json",
      tagColors: ["gray"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/json/sample-demo.json",
      },
    },
    {
      id: "root_file_archive_zip",
      storageId: "1",
      name: "archive-assets.zip",
      type: "file",
      parentId: undefined,
      size: 8_540_003,
      extension: "zip",
      updatedAt: "2026-04-18T10:30:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/zip",
      tagColors: ["yellow"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/zip/sample-zip-file.zip",
      },
    },
    {
      id: "root_file_sql_dump",
      storageId: "1",
      name: "analytics-dump.sql",
      type: "file",
      parentId: undefined,
      size: 228_440,
      extension: "sql",
      updatedAt: "2026-04-18T10:34:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/sql",
      tagColors: ["red"],
    },
    {
      id: "root_file_palette_json",
      storageId: "1",
      name: "palette-tokens.json",
      type: "file",
      parentId: undefined,
      size: 8_920,
      extension: "json",
      updatedAt: "2026-04-18T10:38:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/json",
      tagColors: ["blue"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/json/sample-demo.json",
      },
    },
    {
      id: "root_file_notes_pdf",
      storageId: "1",
      name: "meeting-notes.pdf",
      type: "file",
      parentId: undefined,
      size: 2_740_000,
      extension: "pdf",
      updatedAt: "2026-04-18T10:42:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/pdf",
      tagColors: ["red"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/pdf/sample-large.pdf",
      },
    },
    {
      id: "root_file_design_brief",
      storageId: "1",
      name: "design-brief.docx",
      type: "file",
      parentId: undefined,
      size: 1_640_220,
      extension: "docx",
      updatedAt: "2026-04-18T10:46:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      tagColors: ["blue"],
      metadata: {
        sourceUrl: "https://calibre-ebook.com/downloads/demos/demo.docx",
      },
    },
    {
      id: "root_file_press_kit",
      storageId: "1",
      name: "press-kit.pdf",
      type: "file",
      parentId: undefined,
      size: 3_080_440,
      extension: "pdf",
      updatedAt: "2026-04-18T10:50:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/pdf",
      tagColors: ["yellow"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/pdf/sample-large.pdf",
      },
    },
    {
      id: "root_file_budget_sheet",
      storageId: "1",
      name: "budget-sheet.xlsx",
      type: "file",
      parentId: undefined,
      size: 920_212,
      extension: "xlsx",
      updatedAt: "2026-04-18T10:54:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      tagColors: ["green"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/xlsx/sample-500kb.xlsx",
      },
    },
    {
      id: "root_file_sizzle_reel",
      storageId: "1",
      name: "sizzle-reel.mp4",
      type: "file",
      parentId: undefined,
      size: 12_340_000,
      extension: "mp4",
      updatedAt: "2026-04-18T10:58:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/mp4",
      tagColors: ["green"],
      metadata: {
        previewUrl: "https://download.samplelib.com/mp4/sample-5s.mp4",
        sourceUrl: "https://download.samplelib.com/mp4/sample-5s.mp4",
      },
    },
    {
      id: "file_logo_png",
      storageId: "1",
      name: "logo-system.png",
      type: "file",
      parentId: "folder_brand",
      size: 2_458_122,
      extension: "png",
      updatedAt: "2026-04-12T09:15:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/png",
      tagColors: ["blue"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg",
      },
    },
    {
      id: "file_brand_cover_jpg",
      storageId: "1",
      name: "brand-cover.jpg",
      type: "file",
      parentId: "folder_brand",
      size: 3_284_120,
      extension: "jpg",
      updatedAt: "2026-04-12T09:50:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/jpeg",
      tagColors: ["green"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/a/a9/Example.jpg",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/a/a9/Example.jpg",
      },
    },
    {
      id: "file_brand_pdf",
      storageId: "1",
      name: "brand-guidelines.pdf",
      type: "file",
      parentId: "folder_brand",
      size: 18_880_512,
      extension: "pdf",
      updatedAt: "2026-04-12T10:20:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/pdf",
      tagColors: ["red"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/pdf/sample-large.pdf",
      },
    },
    {
      id: "file_launch_mp4",
      storageId: "1",
      name: "launch-teaser.mp4",
      type: "file",
      parentId: "folder_campaign",
      size: 146_773_114,
      extension: "mp4",
      updatedAt: "2026-04-13T18:10:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/mp4",
      tagColors: ["green"],
      metadata: {
        previewUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
        sourceUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
      },
    },
    {
      id: "file_street_cut_mp4",
      storageId: "1",
      name: "street-cut.mp4",
      type: "file",
      parentId: "folder_campaign",
      size: 5_242_880,
      extension: "mp4",
      updatedAt: "2026-04-13T18:26:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/mp4",
      tagColors: ["blue"],
      metadata: {
        previewUrl: "https://download.samplelib.com/mp4/sample-5s.mp4",
        sourceUrl: "https://download.samplelib.com/mp4/sample-5s.mp4",
      },
    },
    {
      id: "file_voice_m4a",
      storageId: "1",
      name: "voice-over-draft.m4a",
      type: "file",
      parentId: "folder_campaign",
      size: 12_510_294,
      extension: "m4a",
      updatedAt: "2026-04-13T18:40:00.000Z",
      isHidden: false,
      mediaType: "audio",
      mimeType: "audio/mp4",
      tagColors: ["gray"],
      metadata: {
        sourceUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3",
      },
    },
    {
      id: "file_posts_csv",
      storageId: "1",
      name: "social-calendar.csv",
      type: "file",
      parentId: "folder_social",
      size: 45_120,
      extension: "csv",
      updatedAt: "2026-04-11T14:05:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "text/csv",
      tagColors: ["yellow"],
    },
    {
      id: "file_thumb_webp",
      storageId: "1",
      name: "thumbnail-kit.webp",
      type: "file",
      parentId: "folder_social",
      size: 812_450,
      extension: "webp",
      updatedAt: "2026-04-11T14:20:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/webp",
      tagColors: ["blue"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/1280px-PNG_transparency_demonstration_1.png",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/1280px-PNG_transparency_demonstration_1.png",
      },
    },
    {
      id: "file_social_json",
      storageId: "1",
      name: "publishing-rules.json",
      type: "file",
      parentId: "folder_social",
      size: 18_240,
      extension: "json",
      updatedAt: "2026-04-11T15:05:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/json",
      tagColors: ["gray"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/json/sample-demo.json",
      },
    },
    {
      id: "file_campaign_docx",
      storageId: "1",
      name: "campaign-brief.docx",
      type: "file",
      parentId: "folder_campaign",
      size: 2_140_200,
      extension: "docx",
      updatedAt: "2026-04-13T17:48:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType:
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      tagColors: ["blue"],
      metadata: {
        sourceUrl: "https://calibre-ebook.com/downloads/demos/demo.docx",
      },
    },
    {
      id: "file_campaign_storyboard_txt",
      storageId: "1",
      name: "storyboard-outline.txt",
      type: "file",
      parentId: "folder_campaign",
      size: 18_020,
      extension: "txt",
      updatedAt: "2026-04-13T17:58:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "text/plain",
      tagColors: ["gray"],
      metadata: {
        sourceUrl:
          "https://www.w3.org/TR/PNG/iso_8859-1.txt",
      },
    },
    {
      id: "folder_sales",
      storageId: "2",
      name: "Sales Collateral",
      type: "folder",
      parentId: undefined,
      updatedAt: "2026-04-10T08:00:00.000Z",
      isHidden: false,
      tagColors: ["red"],
    },
    {
      id: "file_pitch_pptx",
      storageId: "2",
      name: "enterprise-pitch.pptx",
      type: "file",
      parentId: "folder_sales",
      size: 25_428_000,
      extension: "pptx",
      updatedAt: "2026-04-10T09:00:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType:
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      tagColors: ["yellow"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/ppt/sample-ppt-500kB.ppt",
      },
    },
    {
      id: "file_pricing_xlsx",
      storageId: "2",
      name: "pricing-model.xlsx",
      type: "file",
      parentId: "folder_sales",
      size: 1_202_111,
      extension: "xlsx",
      updatedAt: "2026-04-10T10:30:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      tagColors: ["green"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/xlsx/sample-500kb.xlsx",
      },
    },
    {
      id: "file_case_study_pdf",
      storageId: "2",
      name: "enterprise-case-study.pdf",
      type: "file",
      parentId: "folder_sales",
      size: 2_740_000,
      extension: "pdf",
      updatedAt: "2026-04-10T11:10:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/pdf",
      tagColors: ["red"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/pdf/sample-large.pdf",
      },
    },
    {
      id: "file_walkthrough_mov",
      storageId: "2",
      name: "product-walkthrough.mov",
      type: "file",
      parentId: "folder_sales",
      size: 24_880_120,
      extension: "mov",
      updatedAt: "2026-04-10T11:35:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/quicktime",
      tagColors: ["green"],
      metadata: {
        previewUrl: "https://download.samplelib.com/mp4/sample-10s.mp4",
        sourceUrl: "https://download.samplelib.com/mp4/sample-10s.mp4",
      },
    },
    {
      id: "file_customer_call_mp3",
      storageId: "2",
      name: "customer-call.mp3",
      type: "file",
      parentId: "folder_sales",
      size: 4_280_000,
      extension: "mp3",
      updatedAt: "2026-04-10T11:52:00.000Z",
      isHidden: false,
      mediaType: "audio",
      mimeType: "audio/mpeg",
      tagColors: ["gray"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/mp3/sample-6s.mp3",
      },
    },
    {
      id: "file_contract_zip",
      storageId: "2",
      name: "contract-pack.zip",
      type: "file",
      parentId: "folder_sales",
      size: 8_540_003,
      extension: "zip",
      updatedAt: "2026-04-10T12:03:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/zip",
      tagColors: ["yellow"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/zip/sample-zip-file.zip",
      },
    },
    {
      id: "folder_team",
      storageId: "3",
      name: "Team Notes",
      type: "folder",
      parentId: undefined,
      updatedAt: "2026-04-09T07:30:00.000Z",
      isHidden: false,
      tagColors: ["gray"],
    },
    {
      id: "file_notes_md",
      storageId: "3",
      name: "retro-notes.md",
      type: "file",
      parentId: "folder_team",
      size: 9_240,
      extension: "md",
      updatedAt: "2026-04-09T07:45:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "text/markdown",
      tagColors: ["blue"],
    },
    {
      id: "file_reference_png",
      storageId: "3",
      name: "reference-shot.png",
      type: "file",
      parentId: "folder_team",
      size: 1_104_000,
      extension: "png",
      updatedAt: "2026-04-09T08:10:00.000Z",
      isHidden: false,
      mediaType: "image",
      mimeType: "image/png",
      tagColors: ["yellow"],
      metadata: {
        previewUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Wilhelmshaven_Haven.jpg/1280px-Wilhelmshaven_Haven.jpg",
        sourceUrl:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Wilhelmshaven_Haven.jpg/1280px-Wilhelmshaven_Haven.jpg",
      },
    },
    {
      id: "file_brainstorm_mp3",
      storageId: "3",
      name: "brainstorm-snippet.mp3",
      type: "file",
      parentId: "folder_team",
      size: 102_400,
      extension: "mp3",
      updatedAt: "2026-04-09T08:30:00.000Z",
      isHidden: false,
      mediaType: "audio",
      mimeType: "audio/mpeg",
      tagColors: ["gray"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/mp3/sample-3s.mp3",
      },
    },
    {
      id: "file_team_demo_video",
      storageId: "3",
      name: "team-demo.mp4",
      type: "file",
      parentId: "folder_team",
      size: 14_900_000,
      extension: "mp4",
      updatedAt: "2026-04-09T08:44:00.000Z",
      isHidden: false,
      mediaType: "video",
      mimeType: "video/mp4",
      tagColors: ["green"],
      metadata: {
        previewUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
        sourceUrl:
          "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
      },
    },
    {
      id: "file_team_specs_pdf",
      storageId: "3",
      name: "production-specs.pdf",
      type: "file",
      parentId: "folder_team",
      size: 1_640_120,
      extension: "pdf",
      updatedAt: "2026-04-09T08:52:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/pdf",
      tagColors: ["red"],
      metadata: {
        sourceUrl: "https://download.samplelib.com/pdf/sample-large.pdf",
      },
    },
    {
      id: "file_team_script_doc",
      storageId: "3",
      name: "voice-script.doc",
      type: "file",
      parentId: "folder_team",
      size: 84_220,
      extension: "doc",
      updatedAt: "2026-04-09T09:00:00.000Z",
      isHidden: false,
      mediaType: "file",
      mimeType: "application/msword",
      tagColors: ["blue"],
      metadata: {
        sourceUrl: "https://calibre-ebook.com/downloads/demos/demo.docx",
      },
    },
  ],
});
